import type { Metadata } from "next";
import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar/NavBar";
import Navbar1 from "@/components/NavBar/Navbar1";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Navbar/>
        {children}</body>
    </html>
  );
}
